# Default training configuration
name: small-objects-train

seed: 456123786

datamodule:
  images_dir: ./data/images
  labels_dir: ./data/labels
  batch_size: 16  # Reduced batch size to allow for higher resolution
  num_workers: 0
  val_size: 3
  max_samples: 100

backbone:
  flavor: yolov5s
  pretrained: True
  freeze_depth: 10  # Reduced freeze depth to allow more layers to adapt

model:
  lr: 0.0001
  min_obj_score: 0.001  # Reduced confidence threshold to detect smaller objects
  iou_threshold: 0.90
  confidence_threshold: 0.01

trainer:
  accelerator: mps 
  num_nodes: 1
  max_epochs: 1
  num_sanity_val_steps: 0