# Default training configuration
name: default-train

seed: 456123786

datamodule:
  images_dir: ./data/images
  labels_dir: ./data/labels
  batch_size: 512 
  num_workers: 0
  val_size: 1
  max_samples: 16384

backbone:
  # __target__: src.milleacarinet.model.Yolov5Backbone
  flavor: yolov5s
  pretrained: True
  freeze_depth: 23 

model:
  lr: 0.0001 # learning rate

trainer:
  accelerator: mps 
  num_nodes: 1
  max_epochs: 10